apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: viewer-binding
  namespace: devops-studio
subjects:
- kind: ServiceAccount
  name: viewer-service-account
  namespace: devops-studio
roleRef:
  kind: Role
  name: viewer
  apiGroup: rbac.authorization.k8s.io

