name: Validate Terraform

on:
  push:
    branches: [ main ]
    paths:
      - 'labs/**/*.tf'
      - 'shared/terraform-modules/**/*.tf'
  pull_request:
    branches: [ main ]
    paths:
      - 'labs/**/*.tf'
      - 'shared/terraform-modules/**/*.tf'

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lab: [01-terraform-foundations, 02-kubernetes-platform, 03-cicd-pipelines, 04-observability-stack, 05-security-automation, 06-gitops-workflows, 07-serverless-ops, 08-platform-engineering]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0
    
    - name: Terraform Format Check
      run: terraform fmt -check -recursive labs/${{ matrix.lab }}/
    
    - name: Terraform Init
      run: terraform init -backend=false
      working-directory: labs/${{ matrix.lab }}
    
    - name: Terraform Validate
      run: terraform validate
      working-directory: labs/${{ matrix.lab }}
